### ISSUE TITLE
Undirected Dijkstra not work

### ISSUE THREAD

**Issue by mpperez3** [clue/graph#145] opened 2015-12-07 11:47 UTC
Hi, 
I try to run a Dijkstra walk with one undirected graph but it doesn work. The php script never end. But 
if i try the same example with directed edges it works great.

**Comment by jkuchar** [comment] 2015-12-07 12:24
Please provide code sample. Thanks.

**Comment by mpperez3** [comment] 2015-12-07 17:42
There is one complex example:

 require_once APP . 'Vendor' . DS . 'Graph' . DS . 'autoload.php';
 $graph = new \Fhaculty\Graph\Graph();
$node77 = $graph->createVertex("77");
$node78 = $graph->createVertex("78");
$node79 = $graph->createVertex("79");
$node80 = $graph->createVertex("80");
$node81 = $graph->createVertex("81");
$node82 = $graph->createVertex("82");
$node83 = $graph->createVertex("83");
$node84 = $graph->createVertex("84");
$node85 = $graph->createVertex("85");
$node86 = $graph->createVertex("86");
$node87 = $graph->createVertex("87");
$node88 = $graph->createVertex("88");
$node89 = $graph->createVertex("89");
$node90 = $graph->createVertex("90");
$node91 = $graph->createVertex("91");
$node92 = $graph->createVertex("92");
$node93 = $graph->createVertex("93");
$node94 = $graph->createVertex("94");
$node95 = $graph->createVertex("95");
$node96 = $graph->createVertex("96");
$node97 = $graph->createVertex("97");
$node98 = $graph->createVertex("98");
$node99 = $graph->createVertex("99");
$node100 = $graph->createVertex("100");
$node101 = $graph->createVertex("101");
$node102 = $graph->createVertex("102");
$node103 = $graph->createVertex("103");
$node104 = $graph->createVertex("104");
$node105 = $graph->createVertex("105");
$node106 = $graph->createVertex("106");
$node107 = $graph->createVertex("107");
$node108 = $graph->createVertex("108");
$node109 = $graph->createVertex("109");
$node110 = $graph->createVertex("110");
$node111 = $graph->createVertex("111");
$node112 = $graph->createVertex("112");
$node113 = $graph->createVertex("113");
$node114 = $graph->createVertex("114");
$node115 = $graph->createVertex("115");
$node116 = $graph->createVertex("116");
$node117 = $graph->createVertex("117");
$node118 = $graph->createVertex("118");
$node119 = $graph->createVertex("119");
$node120 = $graph->createVertex("120");
$node121 = $graph->createVertex("121");
$node122 = $graph->createVertex("122");
$node123 = $graph->createVertex("123");
$node388 = $graph->createVertex("388");
$node389 = $graph->createVertex("389");
$node390 = $graph->createVertex("390");
$node391 = $graph->createVertex("391");
$node392 = $graph->createVertex("392");
$node393 = $graph->createVertex("393");
$node394 = $graph->createVertex("394");
$node395 = $graph->createVertex("395");
$node396 = $graph->createVertex("396");
$node397 = $graph->createVertex("397");
$node398 = $graph->createVertex("398");
$node399 = $graph->createVertex("399");
$node400 = $graph->createVertex("400");
$node401 = $graph->createVertex("401");
$node402 = $graph->createVertex("402");
$node403 = $graph->createVertex("403");
$node404 = $graph->createVertex("404");
$node405 = $graph->createVertex("405");
$node406 = $graph->createVertex("406");
$node407 = $graph->createVertex("407");
$node408 = $graph->createVertex("408");
$node409 = $graph->createVertex("409");
$node410 = $graph->createVertex("410");
$node411 = $graph->createVertex("411");
$node412 = $graph->createVertex("412");
$node413 = $graph->createVertex("413");
$node414 = $graph->createVertex("414");
$node415 = $graph->createVertex("415");
$node416 = $graph->createVertex("416");
$node417 = $graph->createVertex("417");
$node418 = $graph->createVertex("418");
$node419 = $graph->createVertex("419");
$node420 = $graph->createVertex("420");
$node421 = $graph->createVertex("421");
$node422 = $graph->createVertex("422");
$node423 = $graph->createVertex("423");
$node424 = $graph->createVertex("424");
$node425 = $graph->createVertex("425");
$node426 = $graph->createVertex("426");
$node427 = $graph->createVertex("427");
$node428 = $graph->createVertex("428");
$node429 = $graph->createVertex("429");
$node430 = $graph->createVertex("430");
$node431 = $graph->createVertex("431");
$node432 = $graph->createVertex("432");
$node433 = $graph->createVertex("433");
$node434 = $graph->createVertex("434");
$node435 = $graph->createVertex("435");
$node436 = $graph->createVertex("436");
$node437 = $graph->createVertex("437");
$node438 = $graph->createVertex("438");
$node439 = $graph->createVertex("439");
$node440 = $graph->createVertex("440");
$node441 = $graph->createVertex("441");
$node442 = $graph->createVertex("442");
$node443 = $graph->createVertex("443");
$node444 = $graph->createVertex("444");
$node445 = $graph->createVertex("445");
$node446 = $graph->createVertex("446");
$node447 = $graph->createVertex("447");
$node448 = $graph->createVertex("448");
$node449 = $graph->createVertex("449");
$node450 = $graph->createVertex("450");
$node451 = $graph->createVertex("451");
$node452 = $graph->createVertex("452");
$node453 = $graph->createVertex("453");
$node454 = $graph->createVertex("454");
$node455 = $graph->createVertex("455");
$node456 = $graph->createVertex("456");
$node457 = $graph->createVertex("457");
$node458 = $graph->createVertex("458");
$node459 = $graph->createVertex("459");
$node460 = $graph->createVertex("460");
$node461 = $graph->createVertex("461");
$node462 = $graph->createVertex("462");
$node463 = $graph->createVertex("463");
$node464 = $graph->createVertex("464");
$node465 = $graph->createVertex("465");
$node466 = $graph->createVertex("466");
$node467 = $graph->createVertex("467");
$node468 = $graph->createVertex("468");
$node469 = $graph->createVertex("469");
$node470 = $graph->createVertex("470");
$node471 = $graph->createVertex("471");
$node472 = $graph->createVertex("472");
$node473 = $graph->createVertex("473");
$node474 = $graph->createVertex("474");
$node475 = $graph->createVertex("475");
$node476 = $graph->createVertex("476");
$node477 = $graph->createVertex("477");
$node478 = $graph->createVertex("478");
$node479 = $graph->createVertex("479");
$node480 = $graph->createVertex("480");
$node481 = $graph->createVertex("481");
$node482 = $graph->createVertex("482");
$node483 = $graph->createVertex("483");
$node484 = $graph->createVertex("484");
$node485 = $graph->createVertex("485");
$node486 = $graph->createVertex("486");
$node487 = $graph->createVertex("487");
$node488 = $graph->createVertex("488");
$node489 = $graph->createVertex("489");
$node490 = $graph->createVertex("490");
$node491 = $graph->createVertex("491");
$node492 = $graph->createVertex("492");
$node493 = $graph->createVertex("493");
$node494 = $graph->createVertex("494");
$node495 = $graph->createVertex("495");
$node496 = $graph->createVertex("496");
$node497 = $graph->createVertex("497");
$node498 = $graph->createVertex("498");
$node499 = $graph->createVertex("499");
$node500 = $graph->createVertex("500");
$node501 = $graph->createVertex("501");
$node502 = $graph->createVertex("502");
$node503 = $graph->createVertex("503");
$node504 = $graph->createVertex("504");
$node505 = $graph->createVertex("505");
$node506 = $graph->createVertex("506");
$node507 = $graph->createVertex("507");
$node508 = $graph->createVertex("508");
$node509 = $graph->createVertex("509");
$node510 = $graph->createVertex("510");
$node511 = $graph->createVertex("511");
$node512 = $graph->createVertex("512");
$node513 = $graph->createVertex("513");
$node514 = $graph->createVertex("514");
$node515 = $graph->createVertex("515");
$node516 = $graph->createVertex("516");
$node517 = $graph->createVertex("517");
$node518 = $graph->createVertex("518");
$node519 = $graph->createVertex("519");
$node520 = $graph->createVertex("520");
$node521 = $graph->createVertex("521");
$node522 = $graph->createVertex("522");
$node523 = $graph->createVertex("523");
$node524 = $graph->createVertex("524");
$node525 = $graph->createVertex("525");
$node526 = $graph->createVertex("526");
$node527 = $graph->createVertex("527");
$node528 = $graph->createVertex("528");
$node529 = $graph->createVertex("529");
$node530 = $graph->createVertex("530");
$node531 = $graph->createVertex("531");
$node532 = $graph->createVertex("532");
$node533 = $graph->createVertex("533");
$node534 = $graph->createVertex("534");
$node535 = $graph->createVertex("535");
$node536 = $graph->createVertex("536");
$node537 = $graph->createVertex("537");
$node538 = $graph->createVertex("538");
$node539 = $graph->createVertex("539");
$node540 = $graph->createVertex("540");
$node541 = $graph->createVertex("541");
$node542 = $graph->createVertex("542");
$node543 = $graph->createVertex("543");
$node544 = $graph->createVertex("544");
$node545 = $graph->createVertex("545");
$node546 = $graph->createVertex("546");
$node547 = $graph->createVertex("547");
$node548 = $graph->createVertex("548");
$node549 = $graph->createVertex("549");
$node550 = $graph->createVertex("550");
$node551 = $graph->createVertex("551");
$node552 = $graph->createVertex("552");
$node553 = $graph->createVertex("553");
$node554 = $graph->createVertex("554");
$node555 = $graph->createVertex("555");
$node556 = $graph->createVertex("556");
$node557 = $graph->createVertex("557");
$node558 = $graph->createVertex("558");
$node559 = $graph->createVertex("559");
$node560 = $graph->createVertex("560");
$node561 = $graph->createVertex("561");
$node562 = $graph->createVertex("562");
$node563 = $graph->createVertex("563");
$node564 = $graph->createVertex("564");
$node565 = $graph->createVertex("565");
$node566 = $graph->createVertex("566");
$node567 = $graph->createVertex("567");
$node568 = $graph->createVertex("568");
$node569 = $graph->createVertex("569");
$node570 = $graph->createVertex("570");
$node571 = $graph->createVertex("571");
$node572 = $graph->createVertex("572");
$node573 = $graph->createVertex("573");
$node574 = $graph->createVertex("574");
$node575 = $graph->createVertex("575");
$node576 = $graph->createVertex("576");
$node577 = $graph->createVertex("577");
$node578 = $graph->createVertex("578");
$node579 = $graph->createVertex("579");
$node580 = $graph->createVertex("580");
$node581 = $graph->createVertex("581");
$node582 = $graph->createVertex("582");
$node583 = $graph->createVertex("583");
$node584 = $graph->createVertex("584");
$node585 = $graph->createVertex("585");
$node586 = $graph->createVertex("586");
$node587 = $graph->createVertex("587");
$node588 = $graph->createVertex("588");
$node589 = $graph->createVertex("589");
$node590 = $graph->createVertex("590");
$node591 = $graph->createVertex("591");
$node592 = $graph->createVertex("592");
$node593 = $graph->createVertex("593");
$node594 = $graph->createVertex("594");
$node595 = $graph->createVertex("595");
$node596 = $graph->createVertex("596");
$node597 = $graph->createVertex("597");
$node84->createEdge($node110);
$node82->createEdge($node104);
$node84->createEdge($node106);
$node77->createEdge($node110);
$node86->createEdge($node110);
$node84->createEdge($node94);
$node84->createEdge($node95);
$node84->createEdge($node93);
$node84->createEdge($node104);
$node84->createEdge($node104);
$node84->createEdge($node113);
$node84->createEdge($node106);
$node84->createEdge($node79);
$node84->createEdge($node101);
$node84->createEdge($node100);
$node84->createEdge($node92);
$node84->createEdge($node116);
$node84->createEdge($node117);
$node84->createEdge($node118);
$node84->createEdge($node92);
$node84->createEdge($node119);
$node84->createEdge($node120);
$node84->createEdge($node115);
$node84->createEdge($node115);
$node84->createEdge($node100);
$node84->createEdge($node81);
$node84->createEdge($node112);
$node84->createEdge($node96);
$node84->createEdge($node105);
$node84->createEdge($node121);
$node84->createEdge($node122);
$node84->createEdge($node123);
$node84->createEdge($node122);
$node84->createEdge($node91);
$node84->createEdge($node106);
$node84->createEdge($node112);
$node90->createEdge($node84);
$node90->createEdge($node81);
$node84->createEdge($node109);
$node84->createEdge($node105);
$node84->createEdge($node102);
$node84->createEdge($node103);
$node88->createEdge($node89);
$node87->createEdge($node78);
$node78->createEdge($node85);
$node87->createEdge($node78);
$node87->createEdge($node85);
$node84->createEdge($node98);
$node80->createEdge($node89);
$node84->createEdge($node111);
$node84->createEdge($node100);
$node84->createEdge($node108);
$node84->createEdge($node97);
$node84->createEdge($node99);
$node83->createEdge($node114);
$node84->createEdge($node107);
$node389->createEdge($node501);
$node389->createEdge($node501);
$node389->createEdge($node511);
$node389->createEdge($node511);
$node389->createEdge($node512);
$node389->createEdge($node512);
$node389->createEdge($node580);
$node389->createEdge($node580);
$node389->createEdge($node547);
$node389->createEdge($node547);
$node389->createEdge($node526);
$node389->createEdge($node526);
$node464->createEdge($node582);
$node394->createEdge($node549);
$node394->createEdge($node465);
$node465->createEdge($node549);
$node465->createEdge($node522);
$node465->createEdge($node561);
$node84->createEdge($node491);
$node84->createEdge($node574);
$node84->createEdge($node587);
$node480->createEdge($node481);
$node480->createEdge($node482);
$node481->createEdge($node482);
$node77->createEdge($node574);
$node86->createEdge($node574);
$node468->createEdge($node574);
$node431->createEdge($node501);
$node431->createEdge($node531);
$node431->createEdge($node592);
$node431->createEdge($node519);
$node431->createEdge($node526);
$node417->createEdge($node400);
$node423->createEdge($node401);
$node417->createEdge($node574);
$node400->createEdge($node574);
$node423->createEdge($node574);
$node401->createEdge($node574);
$node392->createEdge($node574);
$node392->createEdge($node504);
$node392->createEdge($node581);
$node84->createEdge($node514);
$node84->createEdge($node516);
$node84->createEdge($node567);
$node84->createEdge($node592);
$node84->createEdge($node496);
$node84->createEdge($node497);
$node84->createEdge($node539);
$node469->createEdge($node514);
$node469->createEdge($node516);
$node469->createEdge($node567);
$node469->createEdge($node592);
$node469->createEdge($node539);
$node469->createEdge($node496);
$node469->createEdge($node497);
$node446->createEdge($node526);
$node446->createEdge($node514);
$node446->createEdge($node531);
$node446->createEdge($node498);
$node446->createEdge($node592);
$node446->createEdge($node568);
$node446->createEdge($node588);
$node446->createEdge($node489);
$node445->createEdge($node526);
$node445->createEdge($node514);
$node445->createEdge($node531);
$node445->createEdge($node498);
$node445->createEdge($node592);
$node445->createEdge($node568);
$node445->createEdge($node588);
$node445->createEdge($node489);
$node444->createEdge($node526);
$node444->createEdge($node514);
$node444->createEdge($node531);
$node444->createEdge($node498);
$node444->createEdge($node592);
$node444->createEdge($node568);
$node444->createEdge($node588);
$node444->createEdge($node489);
$node450->createEdge($node526);
$node450->createEdge($node514);
$node450->createEdge($node531);
$node450->createEdge($node498);
$node450->createEdge($node592);
$node450->createEdge($node568);
$node450->createEdge($node588);
$node450->createEdge($node489);
$node449->createEdge($node526);
$node449->createEdge($node514);
$node449->createEdge($node531);
$node449->createEdge($node498);
$node449->createEdge($node592);
$node449->createEdge($node568);
$node449->createEdge($node588);
$node449->createEdge($node489);
$node431->createEdge($node563);
$node431->createEdge($node578);
$node431->createEdge($node492);
$node431->createEdge($node556);
$node431->createEdge($node502);
$node84->createEdge($node566);
$node84->createEdge($node566);
$node84->createEdge($node566);
$node84->createEdge($node511);
$node431->createEdge($node550);
$node431->createEdge($node550);
$node431->createEdge($node548);
$node431->createEdge($node510);
$node431->createEdge($node583);
$node431->createEdge($node515);
$node431->createEdge($node499);
$node431->createEdge($node513);
$node431->createEdge($node559);
$node431->createEdge($node584);
$node431->createEdge($node557);
$node431->createEdge($node572);
$node431->createEdge($node573);
$node431->createEdge($node576);
$node431->createEdge($node577);
$node431->createEdge($node575);
$node431->createEdge($node578);
$node431->createEdge($node101);
$node431->createEdge($node532);
$node431->createEdge($node562);
$node431->createEdge($node558);
$node431->createEdge($node533);
$node431->createEdge($node520);
$node431->createEdge($node108);
$node431->createEdge($node81);
$node431->createEdge($node506);
$node431->createEdge($node507);
$node431->createEdge($node594);
$node431->createEdge($node505);
$node431->createEdge($node551);
$node431->createEdge($node109);
$node431->createEdge($node552);
$node431->createEdge($node553);
$node431->createEdge($node490);
$node431->createEdge($node590);
$node431->createEdge($node543);
$node431->createEdge($node591);
$node431->createEdge($node523);
$node431->createEdge($node490);
$node465->createEdge($node525);
$node476->createEdge($node554);
$node476->createEdge($node567);
$node476->createEdge($node565);
$node476->createEdge($node541);
$node466->createEdge($node586);
$node401->createEdge($node548);
$node421->createEdge($node548);
$node401->createEdge($node420);
$node401->createEdge($node421);
$node419->createEdge($node420);
$node419->createEdge($node421);
$node420->createEdge($node421);
$node401->createEdge($node419);
$node476->createEdge($node408);
$node476->createEdge($node567);
$node408->createEdge($node567);
$node426->createEdge($node497);
$node426->createEdge($node539);
$node426->createEdge($node514);
$node426->createEdge($node516);
$node426->createEdge($node567);
$node426->createEdge($node592);
$node84->createEdge($node112);
$node406->createEdge($node407);
$node476->createEdge($node503);
$node476->createEdge($node503);
$node476->createEdge($node568);
$node476->createEdge($node592);
$node476->createEdge($node508);
$node476->createEdge($node539);
$node476->createEdge($node592);
$node404->createEdge($node516);
$node404->createEdge($node524);
$node404->createEdge($node497);
$node404->createEdge($node542);
$node404->createEdge($node592);
$node419->createEdge($node108);
$node419->createEdge($node420);
$node419->createEdge($node421);
$node419->createEdge($node432);
$node420->createEdge($node421);
$node420->createEdge($node432);
$node420->createEdge($node108);
$node485->createEdge($node516);
$node485->createEdge($node524);
$node485->createEdge($node539);
$node485->createEdge($node542);
$node485->createEdge($node592);
$node485->createEdge($node565);
$node404->createEdge($node550);
$node404->createEdge($node567);
$node399->createEdge($node511);
$node398->createEdge($node511);
$node436->createEdge($node511);
$node404->createEdge($node564);
$node432->createEdge($node530);
$node432->createEdge($node534);
$node84->createEdge($node535);
$node403->createEdge($node592);
$node434->createEdge($node592);
$node476->createEdge($node395);
$node476->createEdge($node592);
$node476->createEdge($node539);
$node394->createEdge($node571);
$node409->createEdge($node545);
$node434->createEdge($node545);
$node469->createEdge($node545);
$node442->createEdge($node504);
$node443->createEdge($node546);
$node442->createEdge($node574);
$node443->createEdge($node560);
$node390->createEdge($node592);
$node476->createEdge($node586);
$node421->createEdge($node504);
$node421->createEdge($node536);
$node421->createEdge($node574);
$node421->createEdge($node560);
$node421->createEdge($node120);
$node421->createEdge($node546);
$node421->createEdge($node495);
$node421->createEdge($node597);
$node84->createEdge($node112);
$node84->createEdge($node433);
$node447->createEdge($node448);
$node447->createEdge($node391);
$node448->createEdge($node391);
$node84->createEdge($node595);
$node84->createEdge($node596);
$node477->createEdge($node586);
$node84->createEdge($node535);
$node84->createEdge($node108);
$node395->createEdge($node592);
$node421->createEdge($node537);
$node421->createEdge($node538);
$node410->createEdge($node539);
$node410->createEdge($node542);
$node410->createEdge($node586);
$node410->createEdge($node592);
$node479->createEdge($node465);
$node479->createEdge($node84);
$node479->createEdge($node108);
$node479->createEdge($node81);
$node440->createEdge($node465);
$node440->createEdge($node84);
$node440->createEdge($node108);
$node440->createEdge($node81);
$node465->createEdge($node84);
$node465->createEdge($node108);
$node465->createEdge($node81);
$node84->createEdge($node108);
$node84->createEdge($node81);
$node411->createEdge($node84);
$node411->createEdge($node535);
$node411->createEdge($node108);
$node484->createEdge($node89);
$node84->createEdge($node109);
$node84->createEdge($node593);
$node84->createEdge($node569);
$node439->createEdge($node393);
$node439->createEdge($node84);
$node439->createEdge($node465);
$node431->createEdge($node433);
$node430->createEdge($node433);
$node431->createEdge($node498);
$node430->createEdge($node498);
$node84->createEdge($node544);
$node432->createEdge($node497);
$node432->createEdge($node494);
$node432->createEdge($node526);
$node432->createEdge($node588);
$node80->createEdge($node483);
$node78->createEdge($node545);
$node84->createEdge($node545);
$node465->createEdge($node545);
$node409->createEdge($node545);
$node429->createEdge($node545);
$node434->createEdge($node545);
$node438->createEdge($node545);
$node455->createEdge($node545);
$node437->createEdge($node545);
$node469->createEdge($node545);
$node418->createEdge($node545);
$node416->createEdge($node545);
$node435->createEdge($node545);
$node405->createEdge($node545);
$node422->createEdge($node545);
$node451->createEdge($node545);
$node441->createEdge($node545);
$node486->createEdge($node568);
$node488->createEdge($node568);
$node487->createEdge($node568);
$node432->createEdge($node527);
$node84->createEdge($node514);
$node84->createEdge($node592);
$node84->createEdge($node514);
$node84->createEdge($node592);
$node465->createEdge($node549);
$node475->createEdge($node498);
$node475->createEdge($node498);
$node84->createEdge($node498);
$node84->createEdge($node521);
$node84->createEdge($node592);
$node84->createEdge($node542);
$node84->createEdge($node526);
$node436->createEdge($node498);
$node436->createEdge($node521);
$node436->createEdge($node592);
$node436->createEdge($node542);
$node436->createEdge($node526);
$node402->createEdge($node550);
$node428->createEdge($node500);
$node428->createEdge($node514);
$node428->createEdge($node521);
$node428->createEdge($node542);
$node428->createEdge($node585);
$node398->createEdge($node500);
$node398->createEdge($node514);
$node398->createEdge($node521);
$node398->createEdge($node542);
$node398->createEdge($node585);
$node84->createEdge($node500);
$node84->createEdge($node514);
$node84->createEdge($node521);
$node84->createEdge($node542);
$node84->createEdge($node585);
$node428->createEdge($node514);
$node428->createEdge($node521);
$node428->createEdge($node585);
$node398->createEdge($node500);
$node398->createEdge($node514);
$node398->createEdge($node521);
$node398->createEdge($node542);
$node398->createEdge($node585);
$node84->createEdge($node514);
$node84->createEdge($node521);
$node84->createEdge($node542);
$node84->createEdge($node585);
$node84->createEdge($node494);
$node84->createEdge($node542);
$node412->createEdge($node580);
$node412->createEdge($node540);
$node413->createEdge($node580);
$node413->createEdge($node540);
$node452->createEdge($node580);
$node452->createEdge($node540);
$node453->createEdge($node580);
$node453->createEdge($node540);
$node478->createEdge($node498);
$node478->createEdge($node540);
$node478->createEdge($node580);
$node478->createEdge($node592);
$node478->createEdge($node579);
$node478->createEdge($node498);
$node478->createEdge($node540);
$node478->createEdge($node580);
$node478->createEdge($node592);
$node478->createEdge($node579);
$node427->createEdge($node521);
$node427->createEdge($node586);
$node398->createEdge($node521);
$node398->createEdge($node542);
$node398->createEdge($node586);
$node398->createEdge($node514);
$node398->createEdge($node500);
$node398->createEdge($node521);
$node398->createEdge($node586);
$node398->createEdge($node500);
$node428->createEdge($node521);
$node428->createEdge($node542);
$node428->createEdge($node586);
$node428->createEdge($node514);
$node428->createEdge($node500);
$node428->createEdge($node521);
$node428->createEdge($node514);
$node84->createEdge($node521);
$node84->createEdge($node542);
$node84->createEdge($node586);
$node84->createEdge($node514);
$node84->createEdge($node500);
$node84->createEdge($node586);
$node84->createEdge($node500);
$node473->createEdge($node493);
$node474->createEdge($node493);
$node469->createEdge($node542);
$node469->createEdge($node465);
$node469->createEdge($node542);
$node469->createEdge($node465);
$node397->createEdge($node568);
$node397->createEdge($node517);
$node397->createEdge($node541);
$node397->createEdge($node496);
$node397->createEdge($node511);
$node83->createEdge($node114);
$node388->createEdge($node518);
$node388->createEdge($node120);
$node388->createEdge($node578);
$node388->createEdge($node575);
$node414->createEdge($node396);
$node414->createEdge($node415);
$node415->createEdge($node396);
$node454->createEdge($node588);
$node461->createEdge($node592);
$node459->createEdge($node592);
$node460->createEdge($node592);
$node456->createEdge($node592);
$node458->createEdge($node592);
$node457->createEdge($node592);
$node461->createEdge($node509);
$node459->createEdge($node509);
$node460->createEdge($node509);
$node456->createEdge($node509);
$node458->createEdge($node509);
$node457->createEdge($node509);
$node461->createEdge($node541);
$node459->createEdge($node541);
$node460->createEdge($node541);
$node456->createEdge($node541);
$node458->createEdge($node541);
$node457->createEdge($node541);
$node461->createEdge($node539);
$node459->createEdge($node539);
$node460->createEdge($node539);
$node456->createEdge($node539);
$node458->createEdge($node539);
$node457->createEdge($node539);
$node463->createEdge($node580);
$node467->createEdge($node580);
$node463->createEdge($node531);
$node467->createEdge($node531);
$node423->createEdge($node517);
$node423->createEdge($node542);
$node423->createEdge($node589);
$node423->createEdge($node592);
$node424->createEdge($node517);
$node424->createEdge($node542);
$node424->createEdge($node589);
$node424->createEdge($node592);
$node425->createEdge($node517);
$node425->createEdge($node542);
$node425->createEdge($node589);
$node425->createEdge($node592);
$node421->createEdge($node574);
$node432->createEdge($node574);
$node420->createEdge($node574);
$node421->createEdge($node491);
$node432->createEdge($node491);
$node421->createEdge($node432);
$node470->createEdge($node570);
$node471->createEdge($node570);
$node472->createEdge($node570);
$node471->createEdge($node470);
$node462->createEdge($node494);
$node462->createEdge($node496);
$node462->createEdge($node528);
$node462->createEdge($node531);
$node462->createEdge($node529);
$node462->createEdge($node555);
$node462->createEdge($node592);

//this never ends
        $dj = new Graphp\Algorithms\ShortestPath\Dijkstra($node87);
        try {
            $walk = $dj->getWalkTo($node400);
        } catch (Exception $e) {
            return null;
        }
//this ends
 $dj = new Graphp\Algorithms\ShortestPath\Dijkstra($node87);
        try {
            $walk = $dj->getWalkTo($node78);
        } catch (Exception $e) {
            return null;
        }

thanks for your time :)

**Comment by clue** [comment] 2015-12-10 17:43
Thanks for reporting @mpperez3! I believe this to be a duplicate of https://github.com/graphp/algorithms/issues/9.

As such, I consider this to be a new feature request, not a bug report (Dijkstra has never been designed for undirected edges, though we failed to add clear documentation about this).

If anybody feels like picking up https://github.com/graphp/algorithms/issues/9 that would be super awesome! :+1:

**Closed by clue** 2015-12-10 17:43 UTC
